name: uri_content
description: Get the Uint8List content of a given Uri. Supports file, data, content and http/https
version: 2.2.1
homepage: https://github.com/talesbarreto/uri_content
topics:
  - uri
  - download
  - content
  - uint8list

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <6.0.0"
  pigeon: ">=15.0.2 <25.0.0"
  plugin_platform_interface: ^2.1.4
  mocktail: ^1.0.2
  pull_request_coverage: ">=1.3.5 <3.0.0"
  lints: ">=2.1.1 <6.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.talesbarreto.uri_content
        pluginClass: UriContentPlugin
      ios:
        pluginClass: UriContentPlugin
      linux:
        pluginClass: UriContentPlugin
      macos:
        pluginClass: UriContentPlugin
      windows:
        pluginClass: UriContentPluginCApi
